Minor fixes to make it easy to run locally.
* ingest.py and ingest_examples.py raise an exception trying to delete the schemas

  * Catch these exceptions and keep going
  * My guess is the code was written as though the schemas had already been created and therefore wants to recreate them
  * This causes the aforementioned exceptions when starting with a fresh weaviate cluster

* Here's an example exception

  Traceback (most recent call last):
  File "/Users/jlewi/git_chat-langchain/ingest.py", line 42, in <module>
    client.schema.delete_class("Paragraph")
  File "/opt/homebrew/lib/python3.10/site-packages/weaviate/schema/crud_schema.py", line 201, in delete_class
    raise UnexpectedStatusCodeException("Delete class from schema", response)
weaviate.exceptions.UnexpectedStatusCodeException: Delete class from schema! Unexpected status code: 400, with response body: {'error': [{'message': "could not find class 'Paragraph'"}]}.

* Update ingest.sh to check if the documents have already been downloaded.
* Update the README.md with instructions about how to deploy it yourself.

* Add a .gitignore file